platform :ios, '9.0'

target 'project_v1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for project_v1

    pod 'SwiftyJSON'
    pod 'Alamofire'

end
